/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JInternalFrame.java to edit this template
 */
package formularios;

import dao.DaoProducto;
import javax.swing.JOptionPane;
import modelos.Producto;

/**
 *
 * @author jhonj
 */
public class CrearProducto extends javax.swing.JInternalFrame {

    /**
     * Creates new form CrearProducto
     */
    public CrearProducto() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        panelCabeceraCrearPro = new javax.swing.JPanel();
        lblCrearPro = new javax.swing.JLabel();
        panelCuerpoCrearPro = new javax.swing.JPanel();
        lblNombrePro = new javax.swing.JLabel();
        txtCajaNombrePro = new javax.swing.JTextField();
        lblReferenciaPro = new javax.swing.JLabel();
        txtCajaReferenciaPro = new javax.swing.JTextField();
        lblTemperaturaPro = new javax.swing.JLabel();
        txtCajaTemperatura = new javax.swing.JTextField();
        lblValorBasePro = new javax.swing.JLabel();
        txtCajaValorBasePro = new javax.swing.JTextField();
        panelBotonesCrearPro = new javax.swing.JPanel();
        btnCrearProducto = new javax.swing.JButton();
        btnCancelar = new javax.swing.JButton();

        setClosable(true);
        setTitle("Crear Producto");

        panelCabeceraCrearPro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblCrearPro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblCrearPro.setText("CREAR PRODUCTO");

        javax.swing.GroupLayout panelCabeceraCrearProLayout = new javax.swing.GroupLayout(panelCabeceraCrearPro);
        panelCabeceraCrearPro.setLayout(panelCabeceraCrearProLayout);
        panelCabeceraCrearProLayout.setHorizontalGroup(
            panelCabeceraCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraCrearProLayout.createSequentialGroup()
                .addGap(259, 259, 259)
                .addComponent(lblCrearPro)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        panelCabeceraCrearProLayout.setVerticalGroup(
            panelCabeceraCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCabeceraCrearProLayout.createSequentialGroup()
                .addGap(27, 27, 27)
                .addComponent(lblCrearPro)
                .addContainerGap(31, Short.MAX_VALUE))
        );

        panelCuerpoCrearPro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        lblNombrePro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblNombrePro.setText("NOMBRE: ");

        txtCajaNombrePro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblReferenciaPro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblReferenciaPro.setText("REFERENCIA: ");

        txtCajaReferenciaPro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N

        lblTemperaturaPro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblTemperaturaPro.setText("TEMPERATURA: ");

        txtCajaTemperatura.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCajaTemperatura.setText("0");

        lblValorBasePro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        lblValorBasePro.setText("VALOR BASE: ");

        txtCajaValorBasePro.setFont(new java.awt.Font("Segoe UI", 1, 18)); // NOI18N
        txtCajaValorBasePro.setText("0");

        javax.swing.GroupLayout panelCuerpoCrearProLayout = new javax.swing.GroupLayout(panelCuerpoCrearPro);
        panelCuerpoCrearPro.setLayout(panelCuerpoCrearProLayout);
        panelCuerpoCrearProLayout.setHorizontalGroup(
            panelCuerpoCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoCrearProLayout.createSequentialGroup()
                .addGap(41, 41, 41)
                .addGroup(panelCuerpoCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblReferenciaPro)
                    .addComponent(lblNombrePro)
                    .addComponent(lblTemperaturaPro)
                    .addComponent(lblValorBasePro))
                .addGap(42, 42, 42)
                .addGroup(panelCuerpoCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(txtCajaNombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, 355, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addGroup(panelCuerpoCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING, false)
                        .addComponent(txtCajaValorBasePro, javax.swing.GroupLayout.Alignment.LEADING, javax.swing.GroupLayout.DEFAULT_SIZE, 354, Short.MAX_VALUE)
                        .addComponent(txtCajaTemperatura, javax.swing.GroupLayout.Alignment.LEADING)
                        .addComponent(txtCajaReferenciaPro, javax.swing.GroupLayout.Alignment.LEADING)))
                .addContainerGap(122, Short.MAX_VALUE))
        );
        panelCuerpoCrearProLayout.setVerticalGroup(
            panelCuerpoCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelCuerpoCrearProLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addGroup(panelCuerpoCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblNombrePro)
                    .addComponent(txtCajaNombrePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(26, 26, 26)
                .addGroup(panelCuerpoCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblReferenciaPro)
                    .addComponent(txtCajaReferenciaPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCuerpoCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblTemperaturaPro)
                    .addComponent(txtCajaTemperatura, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(panelCuerpoCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblValorBasePro)
                    .addComponent(txtCajaValorBasePro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(64, Short.MAX_VALUE))
        );

        panelBotonesCrearPro.setBorder(javax.swing.BorderFactory.createEtchedBorder());

        btnCrearProducto.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCrearProducto.setText("CREAR");
        btnCrearProducto.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnCrearProductoActionPerformed(evt);
            }
        });

        btnCancelar.setFont(new java.awt.Font("Segoe UI", 1, 24)); // NOI18N
        btnCancelar.setText("CANCELAR");

        javax.swing.GroupLayout panelBotonesCrearProLayout = new javax.swing.GroupLayout(panelBotonesCrearPro);
        panelBotonesCrearPro.setLayout(panelBotonesCrearProLayout);
        panelBotonesCrearProLayout.setHorizontalGroup(
            panelBotonesCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesCrearProLayout.createSequentialGroup()
                .addGap(40, 40, 40)
                .addComponent(btnCrearProducto)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(btnCancelar)
                .addGap(53, 53, 53))
        );
        panelBotonesCrearProLayout.setVerticalGroup(
            panelBotonesCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(panelBotonesCrearProLayout.createSequentialGroup()
                .addGap(19, 19, 19)
                .addGroup(panelBotonesCrearProLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(btnCrearProducto)
                    .addComponent(btnCancelar))
                .addContainerGap(33, Short.MAX_VALUE))
        );

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addGroup(layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(panelCuerpoCrearPro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelCabeceraCrearPro, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                    .addComponent(panelBotonesCrearPro, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                .addContainerGap())
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(panelCabeceraCrearPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelCuerpoCrearPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(panelBotonesCrearPro, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void limpiarCajas(){
        txtCajaNombrePro.setText("");
        txtCajaReferenciaPro.setText("");
        txtCajaTemperatura.setText("");
        txtCajaValorBasePro.setText("");
        txtCajaNombrePro.requestFocus();
    }
    
    private void btnCrearProductoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnCrearProductoActionPerformed
        //******************************************************
        //definicion de variables
        //******************************************************
        String cajaNombre, cajaReferencia;
        Double cajaTemperatura, cajaValorBase;
        DaoProducto objDaoProducto;
        Producto objProducto;
        //******************************************************
        //******************************************************
        //capturar datos
        //******************************************************
        cajaNombre = txtCajaNombrePro.getText();
        cajaReferencia = txtCajaReferenciaPro.getText();
        cajaTemperatura = Double.parseDouble(txtCajaTemperatura.getText());
        cajaValorBase = Double.parseDouble(txtCajaValorBasePro.getText());
        //******************************************************
        if (cajaNombre.isEmpty() || cajaReferencia.isEmpty() || cajaTemperatura == 0 || cajaValorBase == 0) {
            JOptionPane.showMessageDialog(panelCuerpoCrearPro, "Todos los valores son obligatorios.");
        } else {
            //****************************************************
            //creacion de objetos
            //****************************************************
            objDaoProducto = new DaoProducto();
            objProducto = new Producto();
            //****************************************************
            objProducto.setNombre(cajaNombre);
            objProducto.setId(cajaReferencia);
            objProducto.setTemperatura(cajaTemperatura);
            objProducto.setValorBase(cajaValorBase);

            if (objDaoProducto.agregar(objProducto)) {
                JOptionPane.showMessageDialog(panelCuerpoCrearPro, "EXITO: Registro agregado correctamente.");
            } else {
                JOptionPane.showMessageDialog(panelCuerpoCrearPro, "ERROR: Registro NO FUE agregado correctamente.");
            }
            limpiarCajas();
        }

    }//GEN-LAST:event_btnCrearProductoActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnCancelar;
    private javax.swing.JButton btnCrearProducto;
    private javax.swing.JLabel lblCrearPro;
    private javax.swing.JLabel lblNombrePro;
    private javax.swing.JLabel lblReferenciaPro;
    private javax.swing.JLabel lblTemperaturaPro;
    private javax.swing.JLabel lblValorBasePro;
    private javax.swing.JPanel panelBotonesCrearPro;
    private javax.swing.JPanel panelCabeceraCrearPro;
    private javax.swing.JPanel panelCuerpoCrearPro;
    private javax.swing.JTextField txtCajaNombrePro;
    private javax.swing.JTextField txtCajaReferenciaPro;
    private javax.swing.JTextField txtCajaTemperatura;
    private javax.swing.JTextField txtCajaValorBasePro;
    // End of variables declaration//GEN-END:variables
}
